
import Head from 'next/head'
import Image from 'next/image'

export const getStaticPaths = async () => {
  return {
    paths: [
      { params: { sid: '1' } },
      { params: { sid: '2' } },
      { params: { sid: '3' } },
    ],
    fallback: false,
  }
}

export const getStaticProps = async ({ params }) => {
  console.log(params)
  const id = params.sid
  let rand = Math.floor(Math.random() * 100)
  return {
    props: {
      name: 'John Doe',
      age: '32',
      rand: rand,
      id: id,
    },
    revalidate: 10,
  }
}





export default function Home({ name, age, rand, id }) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Hello {name}</h1>
        <p>
          You are {age} years old
        </p>
        <p>
          Random number: {rand}
        </p>
        <p>
          ID: {id}
        </p>

      </div>

    </div>
  )
}
